### ISSUE TITLE
docker-compose up --build error

### ISSUE THREAD

**Issue by houxianyj** [mikevandiepen/upgr8#1]
WARNING: The DOCKER_PHP_VERSION variable is not set. Defaulting to a blank string.
WARNING: The DOCKER_CONTAINER_NAME variable is not set. Defaulting to a blank string.
WARNING: The DOCKER_CONTAINER_TIMEZONE variable is not set. Defaulting to a blank string.

**Comment by mikevandiepen** [comment]
Make sure you have the .env which suits your project
`$ cp .env.generic .env` or when using laravel `$ cp .env.laravel .env`

**Comment by houxianyj** [comment]
thinks
