### ISSUE TITLE
How to use xdebug 3

### ISSUE THREAD

**Issue by houxianyj** [mikevandiepen/upgr8#4]
How to use xdebug 3. The problem may be silly. But I can't debug like xdebug 2.
I follow the xdebug document settings. Use phpstorm xdebug, but no effect

**Comment by mikevandiepen** [comment]
I've updated the code since, there were some issues (my bad).. The current setup should be working.

**Comment by houxianyj** [comment]
Thank you for your answer. I think it is my problem.
